// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_J1hBGkBLatNO0gJ9HFxaDvWRTOiSUpA',
    appId: '1:129242841170:web:22e2ba7f5b25ee33da9f8b',
    messagingSenderId: '129242841170',
    projectId: 'workout-videos-18c23',
    authDomain: 'workout-videos-18c23.firebaseapp.com',
    storageBucket: 'workout-videos-18c23.firebasestorage.app',
    measurementId: 'G-QRLZ1K65P2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxYcEdG3Cit9Of_lNq4w084dIeZtOi-rQ',
    appId: '1:129242841170:android:2ca6f53b4dc90aa7da9f8b',
    messagingSenderId: '129242841170',
    projectId: 'workout-videos-18c23',
    storageBucket: 'workout-videos-18c23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-IjGaCMNj8nnx5zW11O2vbD-wHxrU-hQ',
    appId: '1:129242841170:ios:38c8059597fef655da9f8b',
    messagingSenderId: '129242841170',
    projectId: 'workout-videos-18c23',
    storageBucket: 'workout-videos-18c23.firebasestorage.app',
    iosBundleId: 'com.example.fitnessapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-IjGaCMNj8nnx5zW11O2vbD-wHxrU-hQ',
    appId: '1:129242841170:ios:38c8059597fef655da9f8b',
    messagingSenderId: '129242841170',
    projectId: 'workout-videos-18c23',
    storageBucket: 'workout-videos-18c23.firebasestorage.app',
    iosBundleId: 'com.example.fitnessapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_J1hBGkBLatNO0gJ9HFxaDvWRTOiSUpA',
    appId: '1:129242841170:web:3736b2bdd1a08e66da9f8b',
    messagingSenderId: '129242841170',
    projectId: 'workout-videos-18c23',
    authDomain: 'workout-videos-18c23.firebaseapp.com',
    storageBucket: 'workout-videos-18c23.firebasestorage.app',
    measurementId: 'G-PYBQYW6ZZ7',
  );
}
